# Civil War Battles!
Create a numpy array of battle casualties from the first to the last battle:
1245, 2732, 3853, 4824, 5292, 6184, 7282, 81393, 932
Divide the array of battle deaths into 3 arrays - start, middle, and end of the war, each containing 3 elements. Call these arrays warStart, warMiddle and warEnd respectively.
Change the battle death numbers from the first battle to 1405
View that change reflected in the warStart slice
View that change reflected in (i.e. "broadcasted to) the original array


In [1]:
import numpy as np

In [7]:
battles = [1245, 2732, 3853, 4824, 5292, 6184, 7282, 81393, 932]
battles_casualities = np.array(battles)
warStart = battles_casualities[0:3]
warStart

array([1245, 2732, 3853])

In [13]:
battles_casualities = np.array([1245, 2732, 3853, 4824, 5292, 6184, 7282, 81393, 932])
battles_casualities

array([ 1245,  2732,  3853,  4824,  5292,  6184,  7282, 81393,   932])

In [15]:
warStart = battles_casualities[0 :3]
warStart

array([1245, 2732, 3853])

In [16]:
warMiddle = battles_casualities[3:6]
warMiddle

array([4824, 5292, 6184])

In [17]:
warEnd = battles_casualities[6:]
warEnd

array([ 7282, 81393,   932])

In [19]:
battles_casualities[0] = 1405
battles_casualities

array([ 1405,  2732,  3853,  4824,  5292,  6184,  7282, 81393,   932])

In [20]:
warStart

array([1405, 2732, 3853])

## Regiment Information!
Create an array of regiment information 
regimentNames = ['Nighthawks', 'Sky Warriors', 'Rough Riders', 'New Birds’] 
regimentNumber = [1, 2, 3, 4] 
regimentSize = [1092, 2039, 3011, 4099] 
regimentCommander = ['Mitchell', 'Blackthorn', 'Baker', 'Miller’]
regiments = np.array([regimentNames, regimentNumber, regimentSize, regimentCommander]) 
regiments
View the first column of the matrix
View the second row of the matrix
View the top-right quarter of the matrix
What is the average value of the first 2 columns of the second and third rows?
Swap the second and third rows

In [28]:
regimentNames = np.array(['Nighthawks', 'Sky Warriors', 'Rough Riders', 'New Birds'])
regimentNames

array(['Nighthawks', 'Sky Warriors', 'Rough Riders', 'New Birds'],
      dtype='<U12')

In [30]:
regimentNumber = np.array ([1, 2, 3, 4])
regimentNumber

array([1, 2, 3, 4])

In [31]:
regimentSize = np.array([1092, 2039, 3011, 4099])
regimentCommander = np.array(['Mitchell', 'Blackthorn', 'Baker', 'Miller'])
regiments = np.array([regimentNames, regimentNumber, regimentSize, regimentCommander]) 
regiments


array([['Nighthawks', 'Sky Warriors', 'Rough Riders', 'New Birds'],
       ['1', '2', '3', '4'],
       ['1092', '2039', '3011', '4099'],
       ['Mitchell', 'Blackthorn', 'Baker', 'Miller']], dtype='<U12')

In [34]:
regiments_slice = regiments[:,0]
regiments_slice

array(['Nighthawks', '1', '1092', 'Mitchell'], dtype='<U12')

In [36]:
regiments_slice = regiments[1,:]
regiments_slice

array(['1', '2', '3', '4'], dtype='<U12')

In [37]:
regiments_slice = regiments[:2,2:]
regiments_slice

array([['Rough Riders', 'New Birds'],
       ['3', '4']], dtype='<U12')

In [53]:
conversion = regiments[1:3,:2].astype(np.float64)
average = np.mean(conversion)
average

783.5

In [56]:
regiments[1, :], regiments[2, :] = regiments[2, :], regiments[1, :].copy()
regiments

array([['Nighthawks', 'Sky Warriors', 'Rough Riders', 'New Birds'],
       ['1092', '2039', '3011', '4099'],
       ['1', '2', '3', '4'],
       ['Mitchell', 'Blackthorn', 'Baker', 'Miller']], dtype='<U12')

## Creation!
Create an array of the first 10 odd integers.
Create a 10 x 10 arrays of zeros and then "frame" it with a border of ones.
Create a 5x5 array with random values and find the minimum and maximum values
Create a 3x3 identity matrix
Create a random vector of size 30 and find the mean value 
Create a 3x3 matrix with values ranging from 0 to 8
Create a null vector of size 10 but the fifth value which is 1

In [57]:
odd_integers = np.arange(1,20,2)
odd_integers

array([ 1,  3,  5,  7,  9, 11, 13, 15, 17, 19])

In [58]:
zeros_array = np.zeros((10,10))
zeros_array[0,:] = 1
zeros_array[-1,:] = 1
zeros_array[:,0] = 1
zeros_array[:,-1] = 1
zeros_array

array([[1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.]])

In [64]:
random_array = np.random.rand(5, 5)
min = np.min(random_array)
max = np.max(random_array)
random_array

array([[0.4759473 , 0.76619381, 0.62430027, 0.55862271, 0.82439854],
       [0.63443966, 0.68408811, 0.20419571, 0.36855485, 0.5810093 ],
       [0.48049923, 0.37657944, 0.53626658, 0.55110743, 0.39377774],
       [0.44391869, 0.00742711, 0.50694556, 0.84593072, 0.41498791],
       [0.13256086, 0.59006035, 0.72015211, 0.12783495, 0.34173066]])

In [62]:
min

0.04947456151700669

In [63]:
max

0.9696137275808697

In [68]:
identity_matrix = np.eye(5)
identity_matrix

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [70]:
random_vector = np.random.rand(30)
random_vector


array([0.49021188, 0.11189529, 0.59929734, 0.5836401 , 0.18002069,
       0.19815205, 0.94764725, 0.46379568, 0.57848415, 0.15811978,
       0.7777543 , 0.25602351, 0.16020377, 0.11805509, 0.56500172,
       0.40095009, 0.88783585, 0.14874019, 0.358847  , 0.43498686,
       0.24050885, 0.27927366, 0.52672747, 0.26599033, 0.33308468,
       0.15196961, 0.34334341, 0.72178578, 0.30372574, 0.90978273])

In [71]:
np.mean(random_vector)

0.4165284949464643

In [72]:
matrix_range = np.arange(9).reshape(3, 3)
matrix_range

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [73]:
null_vector = np.zeros(10)
null_vector[4] = 1
null_vector

array([0., 0., 0., 0., 1., 0., 0., 0., 0., 0.])

## Sorting!
Find the k smallest values of a NumPy array
Create a random vector of size 10 and sort it

In [75]:
random = np.random.rand(10)
random

array([0.57234176, 0.79121754, 0.63564208, 0.71484869, 0.18398729,
       0.13632652, 0.78601226, 0.3280736 , 0.7724453 , 0.96980384])

In [76]:
sorted_vector = np.sort(random)
sorted_vector

array([0.13632652, 0.18398729, 0.3280736 , 0.57234176, 0.63564208,
       0.71484869, 0.7724453 , 0.78601226, 0.79121754, 0.96980384])

In [77]:
k = 3
k_smallest_values = sorted_vector[:k]
k_smallest_values


array([0.13632652, 0.18398729, 0.3280736 ])

What is the correct syntax for printing the number 50 from the array?!
arr = np.array([[10, 20, 30, 40], [50, 60, 70, 80]])

In [79]:
arr = np.array([[10, 20, 30, 40], [50, 60, 70, 80]])
arr[1,0]

50

## Slicing!
Insert the correct slicing syntax to print the following selection of the array:Every other item from (including) the second item to (not including) the fifth item.

arr = np.array([10, 15, 20, 25, 30, 35, 40])

In [80]:
arr = np.array([10, 15, 20, 25, 30, 35, 40])
arr[1:5:2]

array([15, 25])